name: Deploy Invoicely App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # --------------------
      # Checkout code
      # --------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # --------------------
      # Set up Node.js
      # --------------------
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # --------------------
      # Build Frontend
      # --------------------
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # --------------------
      # Deploy Frontend to Vercel
      # --------------------
      - name: Deploy frontend to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./frontend
          prod: true

      # --------------------
      # Install backend dependencies
      # --------------------
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # --------------------
      # Deploy backend to Render via Deploy Hook
      # --------------------
      - name: Deploy backend to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
